// sentinel_allreduce.cu
//
// One-shot AllReduce using the Sentinel synchronization technique,
// Section IV.B.2 of "Every us Matters: Achieving Near Speed-of-Light Latency
// in GPU Collectives" (arXiv:2607.16100).
//
// Idea (paper, verbatim mechanism): instead of packing a flag with the data
// (as LL does), initialize the receiving scratch slot with a sentinel value
// that is guaranteed not to occur in valid input (the paper's example:
// floating point -NaN). Data is written to the buffer directly, at full
// width -- no flag, no bandwidth halving. The receiver polls the slot until
// its value differs from the sentinel, which is how it detects arrival.
// This preserves full payload bandwidth and uses less scratch than LL
// (Table I: N*D vs 2*N*D), making it more efficient for moderately larger
// messages. The tradeoffs the paper calls out, both implemented faithfully
// here:
//   (a) the buffer must be reset to the sentinel before each reuse
//       (LL doesn't need this, since its flag is a self-clearing epoch), and
//   (b) transmitted values must never legitimately equal the sentinel
//       pattern, or the receiver would mistake real data for "not arrived
//       yet."
//
// This file implements a one-shot (single round) AllReduce-sum across N
// GPUs in push mode:
//   1. Every GPU's scratch buffer is reset to the sentinel bit pattern.
//   2. Every GPU pushes its full input vector directly (no packing) into
//      every peer's scratch buffer.
//   3. Every GPU polls its own scratch buffer until each peer's slot no
//      longer holds the sentinel bit pattern, then reduces (sums).
//
// Build:   make            (see Makefile; requires 2+ NVLink/P2P GPUs)
// Run:     ./sentinel_allreduce [numGPUs] [numFloats] [iters]

#include "../common/gpu_common.cuh"

// A quiet-NaN payload chosen specifically as a sentinel: ordinary reduction
// inputs (uniform floats in [-1, 1], as generated by makeRandomVector, and
// their sums) never produce this exact bit pattern, so "value != sentinel"
// reliably means "real data has arrived." NaN can't be compared with `==`
// under IEEE 754, so we compare raw bits instead -- which is also exactly
// how a real implementation must do it.
__device__ __forceinline__ unsigned int sentinelBits() { return 0x7fdead00u; }
__device__ __forceinline__ float sentinelValue() { return __uint_as_float(sentinelBits()); }

// Resets a GPU's own scratch buffer back to the sentinel before each round.
// This explicit reset step -- and the extra kernel launch it costs -- is
// precisely the "complicates buffer management" drawback the paper
// attributes to Sentinel relative to LL's self-clearing epoch flag.
__global__ void sentinelResetKernel(unsigned int* __restrict__ scratch, size_t count) {
    size_t i = (size_t)blockIdx.x * blockDim.x + threadIdx.x;
    if (i >= count) return;
    scratch[i] = sentinelBits();
}

// Launched on source GPU `self`. Pushes full-width data directly into every
// peer's scratch buffer -- no flag, no packing, full payload bandwidth.
__global__ void sentinelSendKernel(const float* __restrict__ input,
                                    unsigned int** __restrict__ scratchPtrs, int self, int n,
                                    int m) {
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i >= m) return;
    unsigned int bits = __float_as_uint(input[i]);
    for (int p = 0; p < n; ++p) {
        if (p == self) continue;
        unsigned int* dst = scratchPtrs[p] + (size_t)self * m + i;
        *dst = bits;  // single aligned 4-byte store (push)
    }
}

// Launched on GPU `self`. Polls its own (local) scratch buffer until each
// peer's slot no longer reads as the sentinel, then reduces.
__global__ void sentinelRecvReduceKernel(const float* __restrict__ myInput,
                                          const unsigned int* __restrict__ myScratch,
                                          float* __restrict__ output, int self, int n, int m) {
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i >= m) return;

    float sum = myInput[i];
    for (int p = 0; p < n; ++p) {
        if (p == self) continue;
        volatile const unsigned int* src = myScratch + (size_t)p * m + i;
        unsigned int bits;
        do {
            bits = *src;  // busy-poll; volatile forces a fresh load each time
        } while (bits == sentinelBits());
        sum += __uint_as_float(bits);
    }
    output[i] = sum;
}

int main(int argc, char** argv) {
    int nGpusRequested = (argc > 1) ? atoi(argv[1]) : -1;
    size_t M = (argc > 2) ? (size_t)atol(argv[2]) : (1u << 16);  // elements
    int iters = (argc > 3) ? atoi(argv[3]) : 100;

    int N = enablePeerAccessAll(nGpusRequested);
    printf("Sentinel one-shot AllReduce: N=%d GPUs, M=%zu floats (%.1f KB/GPU input)\n", N, M,
           M * sizeof(float) / 1024.0);

    std::vector<std::vector<float>> hostInputs;
    for (int g = 0; g < N; ++g) hostInputs.push_back(makeRandomVector(M, 2000 + g));
    std::vector<float> ref = referenceAllReduceSum(hostInputs);

    std::vector<float*> dInput(N), dOutput(N);
    std::vector<unsigned int*> dScratch(N);
    std::vector<unsigned int**> dScratchPtrTable(N);
    std::vector<cudaStream_t> stream(N);

    for (int g = 0; g < N; ++g) {
        CUDA_CHECK(cudaSetDevice(g));
        CUDA_CHECK(cudaMalloc(&dInput[g], M * sizeof(float)));
        CUDA_CHECK(cudaMalloc(&dOutput[g], M * sizeof(float)));
        CUDA_CHECK(cudaMemcpy(dInput[g], hostInputs[g].data(), M * sizeof(float),
                               cudaMemcpyHostToDevice));
        CUDA_CHECK(cudaMalloc(&dScratch[g], (size_t)N * M * sizeof(unsigned int)));
        CUDA_CHECK(cudaStreamCreate(&stream[g]));
    }
    std::vector<unsigned int*> hostScratchPtrs(N);
    for (int g = 0; g < N; ++g) hostScratchPtrs[g] = dScratch[g];
    for (int g = 0; g < N; ++g) {
        CUDA_CHECK(cudaSetDevice(g));
        CUDA_CHECK(cudaMalloc(&dScratchPtrTable[g], N * sizeof(unsigned int*)));
        CUDA_CHECK(cudaMemcpy(dScratchPtrTable[g], hostScratchPtrs.data(),
                               N * sizeof(unsigned int*), cudaMemcpyHostToDevice));
    }

    const int threads = 256;
    const int blocks = (int)((M + threads - 1) / threads);
    const int resetBlocks = (int)(((size_t)N * M + threads - 1) / threads);

    auto runOnce = [&]() {
        for (int g = 0; g < N; ++g) {
            CUDA_CHECK(cudaSetDevice(g));
            sentinelResetKernel<<<resetBlocks, threads, 0, stream[g]>>>(dScratch[g],
                                                                         (size_t)N * M);
        }
        for (int g = 0; g < N; ++g) {
            CUDA_CHECK(cudaSetDevice(g));
            CUDA_CHECK(cudaStreamSynchronize(stream[g]));  // reset must land before any push
        }
        for (int g = 0; g < N; ++g) {
            CUDA_CHECK(cudaSetDevice(g));
            sentinelSendKernel<<<blocks, threads, 0, stream[g]>>>(dInput[g], dScratchPtrTable[g],
                                                                   g, N, (int)M);
        }
        for (int g = 0; g < N; ++g) {
            CUDA_CHECK(cudaSetDevice(g));
            sentinelRecvReduceKernel<<<blocks, threads, 0, stream[g]>>>(
                dInput[g], dScratch[g], dOutput[g], g, N, (int)M);
        }
        for (int g = 0; g < N; ++g) {
            CUDA_CHECK(cudaSetDevice(g));
            CUDA_CHECK(cudaStreamSynchronize(stream[g]));
        }
    };

    // Correctness check.
    runOnce();
    std::vector<float> got(M);
    CUDA_CHECK(cudaSetDevice(0));
    CUDA_CHECK(cudaMemcpy(got.data(), dOutput[0], M * sizeof(float), cudaMemcpyDeviceToHost));
    bool ok = verify(got, ref);
    printf("Correctness check (rank 0 output vs CPU reference): %s\n",
           ok ? "PASSED" : "FAILED");
    if (N > 1) {
        std::vector<float> got1(M);
        CUDA_CHECK(cudaSetDevice(N - 1));
        CUDA_CHECK(
            cudaMemcpy(got1.data(), dOutput[N - 1], M * sizeof(float), cudaMemcpyDeviceToHost));
        bool ok1 = verify(got1, ref);
        printf("Correctness check (rank %d output vs CPU reference): %s\n", N - 1,
               ok1 ? "PASSED" : "FAILED");
        ok = ok && ok1;
    }

    // Latency loop. The reset kernel + its sync (needed for correctness on
    // reuse) is included in every timed iteration -- this is exactly the
    // "buffer management" cost the paper says Sentinel pays relative to LL.
    WallTimer timer;
    double totalMs = 0;
    for (int it = 0; it < iters; ++it) {
        timer.begin();
        runOnce();
        totalMs += timer.endMs();
    }
    printf("Average one-shot Sentinel AllReduce latency over %d iters: %.3f us\n", iters,
           totalMs * 1000.0 / iters);
    printf("(This includes the sentinel-reset pass each iteration -- see README.)\n");

    for (int g = 0; g < N; ++g) {
        CUDA_CHECK(cudaSetDevice(g));
        cudaFree(dInput[g]);
        cudaFree(dOutput[g]);
        cudaFree(dScratch[g]);
        cudaFree(dScratchPtrTable[g]);
        cudaStreamDestroy(stream[g]);
    }
    return ok ? 0 : 1;
}
